describe('Cypress Testing', ()=> {
  beforeEach(() => {
    cy.intercept('http://localhost:3001/api/v1/orders', {fixture: 'example.json'})
    cy.visit('http://localhost:3000/')
  })

  it('Should run a cypress test', () => {
    expect(true).to.equal(true)
  })

  it('Should have the default orders', () => {
    cy.get('section > :nth-child(1)')
    cy.get(':nth-child(1) > h3').contains('Pat')
    cy.get(':nth-child(1) > .ingredient-list > :nth-child(1)').contains('beans')
    cy.get(':nth-child(1) > .ingredient-list > :nth-child(2)').contains('lettuce')
    cy.get(':nth-child(1) > .ingredient-list > :nth-child(3)').contains('carnitas')
    cy.get(':nth-child(1) > .ingredient-list > :nth-child(4)').contains('queso fresco')
    cy.get(':nth-child(1) > .ingredient-list > :nth-child(5)').contains('jalapeno')
    cy.get('section > :nth-child(2)')
    cy.get(':nth-child(2) > h3').contains('Sam')
    cy.get(':nth-child(2) > .ingredient-list > :nth-child(1)').contains('steak')
    cy.get(':nth-child(2) > .ingredient-list > :nth-child(2)').contains('pico de gallo')
    cy.get(':nth-child(2) > .ingredient-list > :nth-child(3)').contains('lettuce')
    cy.get(':nth-child(2) > .ingredient-list > :nth-child(4)').contains('carnitas')
    cy.get(':nth-child(2) > .ingredient-list > :nth-child(5)').contains('queso fresco')
    cy.get(':nth-child(2) > .ingredient-list > :nth-child(6)').contains('jalapeno')
    cy.get('section > :nth-child(3)')
    cy.get(':nth-child(3) > h3').contains('Alex')
    cy.get(':nth-child(3) > .ingredient-list > :nth-child(1)').contains('sofritas')
    cy.get(':nth-child(3) > .ingredient-list > :nth-child(2)').contains('beans')
    cy.get(':nth-child(3) > .ingredient-list > :nth-child(3)').contains('sour cream')
    cy.get(':nth-child(3) > .ingredient-list > :nth-child(4)').contains('carnitas')
    cy.get(':nth-child(3) > .ingredient-list > :nth-child(5)').contains('queso fresco')
  })

  it('Should have an input box and buttons', () => {
    cy.get('input[type="text"]')
      .type('clem the cat')
      .should('have.value', 'clem the cat')
    cy.get('[name="beans"]').click()
    cy.get('[name="steak"]').click()
    cy.get('[name="carnitas"]').click()
    cy.get('[name="sofritas"]').click()
    cy.get('[name="lettuce"]').click()
    cy.get('[name="queso fresco"]').click()
    cy.get('[name="pico de gallo"]').click()
    cy.get('[name="hot sauce"]').click()
    cy.get('[name="guacamole"]').click()
    cy.get('[name="jalapenos"]').click()
    cy.get('[name="cilantro"]').click()
    cy.get('[name="sour cream"]').click()
    cy.get(':nth-child(15)')
  })

  it('Should Create Clem\'s order!', () => {
    cy.get('input[type="text"]')
      .type('clem the cat')
      .should('have.value', 'clem the cat')
    cy.get('[name="steak"]').click()
    cy.get('[name="carnitas"]').click()
    cy.get('[name="sofritas"]').click()
    cy.get('[name="pico de gallo"]').click()
    cy.get('[name="hot sauce"]').click()
    cy.get('[name="jalapenos"]').click()
    cy.get('[name="cilantro"]').click()
    cy.get(':nth-child(15)').click()
    cy.intercept('http://localhost:3001/api/v1/orders', { fixture: 'postRequest.json' })
    cy.visit('http://localhost:3000/')
  })
  it('Should view clems order upon refresh', () => {
    cy.intercept('http://localhost:3001/api/v1/orders', { fixture: 'postRequest.json' })
    cy.visit('http://localhost:3000/')
  })
})